comics/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import urls as mainURLS
from marvel import urls as marvelURLS


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^marvel/',include(marvelURLS,namespace="marv")),
    url(r'^',include(mainURLS,namespace="main")),
]

main/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^$',views.Home.as_view(),name="home"),
	# url pra  detalles
	# url(r'^(?p<id>[0-9]+)/$', views.DetailView.as_view(), name="detalle")
]

marvel/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^$',
		views.Home.as_view(),
		name="home"),
	
]

main/models.py
from django.db import models

# Create your models here.

marvel/models.py
from django.db import models


class Heroe(models.Model):
	nombre = models.CharField(max_length=140)
	desc = models.TextField()
	img = models.CharField(max_length=500)

	def __str__(self):
		return self.nombre		

main/views.py
from django.shortcuts import render
from django.views.generic import View


class Home(View):
	def get(self,request):
		return render(request,'main/home.html')

marvel/views.py
from django.shortcuts import render
from django.views.generic import View
from .mv import Marvel
from .models import Heroe



class Home(View):
	def get(self,request):
		template_name = 'marvel/home.html'
		return render(request,template_name)

	def post(self,request):
		heroe = request.POST.get('heroe')
		mv = Marvel()
		personaje = mv.get_personaje(heroe)
		link = mv.get_imagen()

		nuevo_p = Heroe.objects.create(nombre=heroe,desc=personaje,img=link)

		template_name = 'marvel/home.html'
		context = {
		'personaje':personaje,
		'heroe':heroe,
		'link':link
		}
		return render(request,template_name,context)

main/templates/main/home.html
{%extends 'base.html'%}

{%block content%}

<section>
	<h2>Bienvenidos Freakys</h2>
	<a href="{%url 'marv:home'%}">Busca tu personaje</a>
</section>

{%endblock content%}

marvel/templates/marvel/home.html
{%extends 'base.html'%}

{%block content%}

	<section>

		{%if personaje%}
		<img style="max-width:200px" src="{{link}}">
		<h2>La descripcion de {{heroe}}: </h2>
		<h3>{{personaje}}</h3>

		{%else%}

		<form action="." method="post">
			<label>
				Escribe el nombre de tu super heroe favorito:
				<input name="heroe" type="text" placeholder="spiderman u otro">
				<input type="submit" value="Pedir">
			</label>
			{%csrf_token%}
		</form>

		{%endif%}

	</section>

{%endblock content%}

templates/base.html
<html>
<head>
	<title>MarvelComics</title>
	<meta chasrset="utf-8">
	<meta name="viewport" content="width=device-width">
	<style type="text/css">
		html, body{
			margin:0;
			padding: 0;
		}
		nav{
			width: 100%;
			height: 64px;
			background: black;
			color: white;
		}
		nav span{
			font-size: 3rem;
			margin-top: 10px;
			transition:all .5s ease-in;
		}
		nav span:hover{
			color: yellow;
			font-size: 4rem;
		}
		section{
			width: 80%;
			margin: 0 auto;
		}
	</style>
</head>
<body>
	<nav>
		<span>Marvel Comics</span>
	</nav>

	{%block content%}
	{%endblock content%}

</body>
</html>